version: '3'
services:
  database:
    image: mongo:3.2.4
    container_name: "talking-statues-database"
    environment:
    - MONGO_DATA_DIR=/data/db
    ports:
    - 27017:27017
    volumes:
    - db-data:/var/lib/mongo/data/db
    networks:
    - backend
  backend:
    build: .
    container_name: "talking-statues-server"
    ports:
    - 9000:8080
    networks:
    - backend
    links:
    - database
volumes:
  db-data:
networks:
  backend: