version: '3'
services:
  database:
    image: mongo:3.4
    container_name: "talking-statues-database"
    ports:
    - 27017:27017
    volumes:
    #- talking-statues-data:/data/db
    - ./config/database/ssl:/etc/ssl
    - ./config/database/script:/docker-entrypoint-initdb.d
    networks:
    - backend
#    environment:
#    - MONGO_INITDB_DATABASE=admin
#    - MONGO_INITDB_ROOT_USERNAME=admin
#    - MONGO_INITDB_ROOT_PASSWORD=admin

  backend:
    build: .
    container_name: "talking-statues-server"
    ports:
    - 9000:8080
    - 8000:8000
    networks:
    - backend
    links:
    - database
volumes:
  talking-statues-data:
networks:
  backend: